"""添加公告表

Revision ID: 3a08fc61773f
Revises: def45678ghi9
Create Date: 2026-05-13 10:19:27.814450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a08fc61773f'
down_revision: Union[str, None] = 'def45678ghi9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('title', sa.String(length=120), nullable=False, comment='公告标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='公告正文'),
    sa.Column('summary', sa.String(length=255), nullable=True, comment='公告摘要'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='级别：info/success/warning/error'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：draft/published/hidden'),
    sa.Column('pinned', sa.Boolean(), nullable=False, comment='是否置顶'),
    sa.Column('author_id', sa.String(length=100), nullable=True, comment='发布管理员ID'),
    sa.Column('author_name', sa.String(length=100), nullable=True, comment='发布管理员显示名'),
    sa.Column('publish_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='发布时间'),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index('idx_announcements_pinned', ['pinned'], unique=False)
        batch_op.create_index('idx_announcements_publish_at', ['publish_at'], unique=False)
        batch_op.create_index('idx_announcements_status', ['status'], unique=False)
        batch_op.create_index('idx_announcements_updated_at', ['updated_at'], unique=False)

    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('task_input',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('task_result',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('progress_details',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index('ix_background_tasks_status')
        batch_op.drop_index('ix_background_tasks_task_type')
        batch_op.create_index(batch_op.f('ix_background_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_user_id'))
        batch_op.create_index('ix_background_tasks_task_type', ['task_type'], unique=False)
        batch_op.create_index('ix_background_tasks_status', ['status'], unique=False)
        batch_op.alter_column('progress_details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('task_result',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('task_input',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index('idx_announcements_updated_at')
        batch_op.drop_index('idx_announcements_status')
        batch_op.drop_index('idx_announcements_publish_at')
        batch_op.drop_index('idx_announcements_pinned')

    op.drop_table('announcements')
    # ### end Alembic commands ###